In [1]:
# Import libraries
import requests
import csv
import pandas as pd

In [7]:
# BSCScan API Setup
def call_api(user):
    URL = "https://api.bscscan.com"
    API_KEY = "W9KUR7P8P2HU1R589IS48X4WVJV5B6Z8XC"
    START_BLOCK = "7906054"
    END_BLOCK = "7915038"
    USER_ADDRESS = user

    endpoint = "{}/api?module=account&action=txlist&address={}&startblock={}&endblock={}&sort=asc&apikey={}".format(URL, USER_ADDRESS, START_BLOCK, END_BLOCK, API_KEY)
    response = requests.get(endpoint)
    JSON_DATA_RAW = response.json()

In [4]:
df = pd.read_csv('maticbridge.csv')
df.head()

,blockNumber,timeStamp,hash,nonce,blockHash,from,contractAddress,to,value,tokenName,tokenSymbol,tokenDecimal,transactionIndex,gas,gasPrice,gasUsed,cumulativeGasUsed,input,confirmations
0,12546134,1622517429,0xed44f1d553920ba941356e2ea5bec716561d2b72e0f0...,2063,0xfdf4b2fd7ad737f3812bd018675df1f289fe18cb417d...,0x40ec5b33f54e0e8a33a975908c5ba1c14e5bbbdf,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0x5583bbda575f142993c10a335daf29dc7510e8f2,500000000,USD Coin,USDC,6,23,272350,28000000000,256470,1411942,deprecated,2137
1,12546135,1622517435,0x394ccda1c0abd5f4189bd3b9bbe3a1a44fb5fcdcd14d...,1,0x5af8a8fc80b3afc9a934acdafbcdf5cefb1d00bceb7e...,0x34400b1418bde0a4f80d7905d14ed39af8d76e79,0xdac17f958d2ee523a2206206994597c13d831ec7,0x40ec5b33f54e0e8a33a975908c5ba1c14e5bbbdf,721782445,Tether USD,USDT,6,74,108181,19715610000,85712,6408537,deprecated,2136
2,12546135,1622517435,0xa190bf069d850a88a2336d25eabe5532096e408faddb...,435,0x5af8a8fc80b3afc9a934acdafbcdf5cefb1d00bceb7e...,0xddbbf84382db98573bcc656fa7c6ac8b52466c8b,0x6b3595068778dd592e39a122f4f5a5cf09c90fe2,0x40ec5b33f54e0e8a33a975908c5ba1c14e5bbbdf,130456595493153042680,SushiToken,SUSHI,18,112,102323,19000000000,79854,9656025,deprecated,2136
3,12546135,1622517435,0x273b4f81dc161bcfd3c0332d35bf3e340146c81d724c...,5,0x5af8a8fc80b3afc9a934acdafbcdf5cefb1d00bceb7e...,0xe60d8c59b0ac3deb73efa0e84747c48038885898,0xdac17f958d2ee523a2206206994597c13d831ec7,0x40ec5b33f54e0e8a33a975908c5ba1c14e5bbbdf,1024556988,Tether USD,USDT,6,131,108181,19000000000,85712,12364809,deprecated,2136
4,12546145,1622517568,0xa270ff5e0d43a20e567973fb6fd28d6294f25d16406f...,504,0x8d1f9ec7383c53c0a073607f5f1e0cfc6f3d9244c45c...,0x1b200c7163826a363b5531016a4f0bc8b0277453,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48,0x40ec5b33f54e0e8a33a975908c5ba1c14e5bbbdf,289669400000,USD Coin,USDC,6,122,114687,23500000000,107218,8693140,deprecated,2126

In [19]:
for index, row in df.head().iterrows():
    USER_ADDRESS = ""
    TYPE = ""
    FLAG = false
    if(row["from"]=="0x40ec5b33f54e0e8a33a975908c5ba1c14e5bbbdf"):
        USER_ADDRESS = row["to"]
        TYPE = "OUT" # Out of Polygon
    else:
        USER_ADDRESS = row["from"]
        TYPE = "IN" # Into Polygon
        
    print(USER_ADDRESS)

0x5583bbda575f142993c10a335daf29dc7510e8f2
0x34400b1418bde0a4f80d7905d14ed39af8d76e79
0xddbbf84382db98573bcc656fa7c6ac8b52466c8b
0xe60d8c59b0ac3deb73efa0e84747c48038885898
0x1b200c7163826a363b5531016a4f0bc8b0277453